#include <stdio.h>
#include <float.h>
#include "srcs/ft_printf.h"
#include <math.h>

//int ft_printf(const char *str, ...);

int main()
{
	printf("FLT_MAX_10_EXP:%.d", FLT_MAX_10_EXP);
	puts("");
	printf("DBL_MAX_10_EXP:%.d", DBL_MAX_10_EXP);
	puts("");
	printf("LDBL_MAX_10_EXP:%.d", LDBL_MAX_10_EXP);
	puts("");
	printf("FLT_MIN_10_EXP:%.d", FLT_MIN_10_EXP);
	puts("");
	printf("DBL_MIN_10_EXP:%.d", DBL_MIN_10_EXP);
	puts("");
	printf("LDBL_MIN_10_EXP:%.d", LDBL_MIN_10_EXP);
	puts("");
	printf("FLT_MAX_EXP:%.d", FLT_MAX_EXP);
	puts("");
	printf("DBL_MAX_EXP:%.d", DBL_MAX_EXP);
	puts("");
	printf("LDBL_MAX_EXP:%.d", LDBL_MAX_EXP);
	puts("");
	printf("FLT_MIN_EXP:%.d", FLT_MIN_EXP);
	puts("");
	printf("DBL_MIN_EXP:%.d", DBL_MIN_EXP);
	puts("");
	printf("LDBL_MIN_EXP:%.d", LDBL_MIN_EXP);
	puts("");
	printf("std:%.20Lg", LDBL_MAX);
	puts("");
	ft_printf("cst:%.20Lg", LDBL_MAX);
	puts("");
	printf("std:%.20g", LDBL_MAX);
	puts("");
	ft_printf("cst:%.20g", LDBL_MAX);
	puts("");
	printf("std:%.20Lg", LDBL_MAX * 10L);
	puts("");
	ft_printf("cst:%.20Lg", LDBL_MAX * 10L);
	puts("");
	printf("std:%.20Lg", LDBL_MAX * 0.1L);
	puts("");
	ft_printf("cst:%.20Lg", LDBL_MAX * 0.1L);
	puts("");
	// printf("std:%.20Lf", LDBL_MAX);
	// puts("");
	// ft_printf("cst:%.20Lf", LDBL_MAX);
	// puts("");
	// printf("std:%.20Le", LDBL_MAX);
	// puts("");
	// ft_printf("cst:%.20Le", LDBL_MAX);
	// puts("");
	printf("std:%.20g", DBL_MAX);
	puts("");
	ft_printf("cst:%.20g", DBL_MAX);
	puts("");
	printf("std:%.20g", DBL_MAX * (double)10);
	puts("");
	ft_printf("cst:%.20g", DBL_MAX * (double)10);
	puts("");
	printf("std:%.20g", DBL_MAX * (double)100);
	puts("");
	ft_printf("cst:%.20g", DBL_MAX * (double)100);
	puts("");
	// printf("std:%.20f", DBL_MAX);
	// puts("");
	// ft_printf("cst:%.20f", DBL_MAX);
	// puts("");
	// printf("std:%.20e", DBL_MAX);
	// puts("");
	// ft_printf("cst:%.20e", DBL_MAX);
	// puts("");
	printf("std:%.20g", FLT_MAX);
	puts("");
	ft_printf("cst:%.20g", FLT_MAX);
	puts("");
	printf("std:%.20g", FLT_MAX * (float)10);
	puts("");
	ft_printf("cst:%.20g", FLT_MAX * (float)10);
	puts("");
	printf("std:%.20g", FLT_MAX * (float)100);
	puts("");
	ft_printf("cst:%.20g", FLT_MAX * (float)100);
	puts("");
	// printf("std:%.20f", FLT_MAX);
	// puts("");
	// ft_printf("cst:%.20f", FLT_MAX);
	// puts("");
	// printf("std:%.20e", FLT_MAX);
	// puts("");
	// ft_printf("cst:%.20e", FLT_MAX);
	// puts("");
	printf("std:%.20Lg", LDBL_MIN);
	puts("");
	ft_printf("cst:%.20Lg", LDBL_MIN);
	puts("");
	printf("std:%.20g", LDBL_MIN);
	puts("");
	ft_printf("cst:%.20g", LDBL_MIN);
	puts("");
	// printf("std:%.16400Lf", LDBL_MIN);
	// puts("");
	// ft_printf("cst:%.16400Lf", LDBL_MIN);
	// puts("");
	// printf("std:%.20Le", LDBL_MIN);
	// puts("");
	// ft_printf("cst:%.20Le", LDBL_MIN);
	// puts("");
	printf("std:%.20g", DBL_MIN);
	puts("");
	ft_printf("cst:%.20g", DBL_MIN);
	puts("");
	printf("std:%.20g", DBL_MIN * (double)0.1);
	puts("");
	ft_printf("cst:%.20g", DBL_MIN * (double)0.1);
	puts("");
	printf("std:%.20g", DBL_MIN * (double)0.01);
	puts("");
	ft_printf("cst:%.20g", DBL_MIN * (double)0.01);
	puts("");
	printf("std:%.20g", DBL_MIN * (double)0.001);
	puts("");
	ft_printf("cst:%.20g", DBL_MIN * (double)0.001);
	puts("");
	printf("std:%.20g", (float)DBL_MIN);
	puts("");
	ft_printf("cst:%.20g", (float)DBL_MIN);
	puts("");
	// printf("std:%.1010f", DBL_MIN);
	// puts("");
	// ft_printf("cst:%.1010f", DBL_MIN);
	// puts("");
	// printf("std:%.20e", DBL_MIN);
	// puts("");
	// ft_printf("cst:%.20e", DBL_MIN);
	// puts("");
	printf("std:%.20g", FLT_MIN);
	puts("");
	ft_printf("cst:%.20g", FLT_MIN);
	puts("");
	printf("std:%.20g", FLT_MIN * (float)0.1);
	puts("");
	ft_printf("cst:%.20g", FLT_MIN * (float)0.1);
	puts("");
	printf("std:%.20g", FLT_MIN * (float)0.01);
	puts("");
	ft_printf("cst:%.20g", FLT_MIN * (float)0.01);
	puts("");
	// printf("std:%.130f", FLT_MIN);
	// puts("");
	// ft_printf("cst:%.130f", FLT_MIN);
	// puts("");
	// printf("std:%.20e", FLT_MIN);
	// puts("");
	// ft_printf("cst:%.20e", FLT_MIN);
	// puts("");
	printf("std:%.20g", FLT_EPSILON);
	puts("");
	ft_printf("cst:%.20g", FLT_EPSILON);
	puts("");
	printf("std:%.20g", FLT_EPSILON * (float)10);
	puts("");
	ft_printf("cst:%.20g", FLT_EPSILON * (float)10);
	puts("");
	printf("std:%.20g", FLT_EPSILON * (float)0.1);
	puts("");
	ft_printf("cst:%.20g", FLT_EPSILON * (float)0.1);
	puts("");
	// printf("std:%.30f", FLT_EPSILON);
	// puts("");
	// ft_printf("cst:%.30f", FLT_EPSILON);
	// puts("");
	// printf("std:%.20e", FLT_EPSILON);
	// puts("");
	// ft_printf("cst:%.20e", FLT_EPSILON);
	// puts("");
	printf("std:%.20g", DBL_EPSILON);
	puts("");
	ft_printf("cst:%.20g", DBL_EPSILON);
	puts("");
	printf("std:%.20g", DBL_EPSILON * (double)10);
	puts("");
	ft_printf("cst:%.20g", DBL_EPSILON * (double)10);
	puts("");
	printf("std:%.20g", DBL_EPSILON * (double)0.1);
	puts("");
	ft_printf("cst:%.20g", DBL_EPSILON * (double)0.1);
	puts("");
	// printf("std:%.65f", DBL_EPSILON);
	// puts("");
	// ft_printf("cst:%.65f", DBL_EPSILON);
	// puts("");
	// printf("std:%.20e", DBL_EPSILON);
	// puts("");
	// ft_printf("cst:%.20e", DBL_EPSILON);
	// puts("");
	printf("std:%.20Lg", LDBL_EPSILON);
	puts("");
	ft_printf("cst:%.20Lg", LDBL_EPSILON);
	puts("");
	printf("std:%.20g", LDBL_EPSILON);
	puts("");
	ft_printf("cst:%.20g", LDBL_EPSILON);
	puts("");
	printf("std:%.20g", LDBL_EPSILON * 0.1L);
	puts("");
	ft_printf("cst:%.20g", LDBL_EPSILON * 0.1L);
	puts("");
	printf("std:%.20g", LDBL_EPSILON * 10L);
	puts("");
	ft_printf("cst:%.20g", LDBL_EPSILON * 10L);
	puts("");
	// printf("std:%.65Lf", LDBL_EPSILON);
	// puts("");
	// ft_printf("cst:%.65Lf", LDBL_EPSILON);
	// puts("");
	// printf("std:%.20Le", LDBL_EPSILON);
	// puts("");
	// ft_printf("cst:%.20Le", LDBL_EPSILON);
	// puts("");
	return (0);
}
